//= error

fun main() {
    std::call("unknown fct");
}