//= error

fun main() {
    std::call("foo");
}

fun foo(a: Int32) {
    println(a.toString());
}
