//= output "Exception\n0: main(): 4\n"

fun main() {
  let e = Exception(nil);
  e.printStackTrace();
}
